[images]
remote_images = [
  "^(?:https:\\/\\/cdn\\.replica\\.tavus\\.io(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
  "^(?:https:\\/\\/tavus-assets\\.s3\\.amazonaws\\.com(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$"
]

[build]
command = "npm run build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

# Headers for static assets
[[headers]]
for = "/_next/static/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# API routes redirect - this must come first
[[redirects]]
from = "/api/*"
to = "/.netlify/functions/___netlify-server-handler"
status = 200

# Image optimization redirects
[[redirects]]
from = "/_next/image"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200
  [redirects.query]
  url = ":url"
  w = ":width"
  q = ":quality"

[[redirects]]
from = "/_ipx/*"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200
  [redirects.query]
  url = ":url"
  w = ":width"
  q = ":quality"

# Catch-all for Next.js pages (must be last)
[[redirects]]
from = "/*"
to = "/.netlify/functions/___netlify-server-handler"
status = 200